### PR TITLE
Added confirmation code to login credentials overview (bunq/tinker_php#25)

### LINKED ISSUE #25: Tinker script user overview returns wrong pincode for phone verification
See https://fe.ax/1535464136-9815f3f04ba8e4549cf1d9f87bc481b2.20180828154856.png

and https://together.bunq.com/d/4077-can-t-get-sandbox-app-to-work

### PR DESCRIPTION
**Pull request by fe-ax**
## This PR closes/fixes the following issues:
 - Closes bunq/tinker_php#25
    - [x] Tested

### CODE REVIEW

**Comment by OGKevin** [comment]
hey @MarcoStuurman thanks for this PR. 

Could you please rebase your commits and include the issue reference in them for issue tracking purposes. As explained here: https://raw.githubusercontent.com/bunq/sdk_php/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by fe-ax** [comment]
Hi @OGKevin, better?

**Review by OGKevin — APPROVED** [review]
Looks good, thanks.

**Comment by OGKevin** [comment]
@andrederoos

**Pull request merged**
