### PR TITLE
fixing UserPerson:update call

### PR DESCRIPTION
**Pull request by goergisn**
adding the user id to the update call to actually make it work

### CODE REVIEW

**Comment by OGKevin** [comment]
Are you sure everything is up to date ? 

The SDK auto determines the User id.

See: https://github.com/bunq/sdk_php/blob/master/src/Model/Generated/Endpoint/UserPerson.php#L698-L734

And hiiiiii btw 😁

**Comment by goergisn** [comment]
Hi :P 

I ran the tinker "install" script from the website about half an hour ago and was faced with:

`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to bunq\Model\Generated\Endpoint\UserPerson::update() must be of the type integer, null given, called in /srv/bunq/src/BunqLib.php on line 468 and defined in /srv/bunq/vendor/bunq/sdk_php/src/Model/Generated/Endpoint/UserPerson.php:698
Stack trace:
#0 /srv/bunq/src/BunqLib.php(468): bunq\Model\Generated\Endpoint\UserPerson::update(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Array)`

when trying to add a callback url 😬

**Comment by OGKevin** [comment]
Ehh, can you check which version of the sdk it installed 🤔

**Comment by goergisn** [comment]
Mhh... ok I can see that it's not the most up to date version apparently as I still have this in there:

`public static function update(
        int $userPersonId,
        string $firstName = null,
        string $middleName = null,`

**Comment by OGKevin** [comment]
Oh I see whats is going on 🤦🏾‍♂️. So composer.lock is locked at `1.0.0` where in `1.0.1` it has been properly regenerated and auto determines the user id. 

So to fix this for you locally, you must run composer update. 

And make an MR that updates the composer.lock 😁

**Comment by goergisn** [comment]
ok cool, closing then :P

**Pull request closed without merging**
